apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeday-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffeeday
  template:
    metadata:
      labels:
        app: coffeeday
    spec:
      containers:
      - name: coffeeday
        image: dadda5/coffeeday
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
